import * as E from 'fp-ts/Either';
import * as O from 'fp-ts/Option';
import { convertPokemonListToCards, getPokemonList } from '@lib/pokeapi';
import { pipe } from 'fp-ts/lib/function';
import { GetServerSidePropsResult } from 'next';
import Head from 'next/head';
import { ReactElement, useState } from 'react';
import { MemoryCardState, Pokemon } from 'app-types';
import { mapWithIndex } from 'fp-ts/lib/Array';
import MemoryCard from '@components/MemoryCard';
import { updateAt } from 'fp-ts/lib/Array';
import { handleClickOnCard } from 'controllers/game-manager';
import { memoryGameState } from 'types/impl';

interface PageProps {
  memoryCardList: MemoryCardState[];
}

export default function Home({ memoryCardList }: PageProps): ReactElement {
  const [cardList, setCardList] = useState<MemoryCardState[]>(memoryCardList);
  const handleClick = (cardIndex: number, cardState: MemoryCardState): void => {
    console.log('Clicked on card', {
      cardIndex,
      cardState,
      newCard: handleClickOnCard({
        cardState,
        gameState: memoryGameState.all_hidden(),
      }),
    });

    setCardList(
      pipe(
        cardList,
        updateAt(
          cardIndex,
          handleClickOnCard({
            cardState,
            gameState: memoryGameState.all_hidden(),
          })
        ),
        O.getOrElse(() => cardList)
      )
    );
  };

  return (
    <div>
      <Head>
        <title>Card Game Poke API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-12 mx-14">
        <h1 className="text-3xl font-bold text-gray-800">
          Welcome to the amazing Card Game Poke API
        </h1>
        <div className="grid grid-cols-4 gap-4 mt-6">
          {pipe(
            cardList,
            mapWithIndex((cardIndex, cardState) => (
              <MemoryCard
                key={cardIndex}
                cardState={cardState}
                handleClick={() => handleClick(cardIndex, cardState)}
              />
            ))
          )}
        </div>
      </div>
    </div>
  );
}

// TODO: Display error message when getPokemonList fails
export async function getServerSideProps(): Promise<
  GetServerSidePropsResult<PageProps>
> {
  return pipe(
    await getPokemonList()(),
    E.getOrElse((): Pokemon[] => []),
    (pokemonList) => ({
      props: { memoryCardList: convertPokemonListToCards(pokemonList) },
    })
  );
}
